### ISSUE TITLE
Rendered lines disappear when CRLF is present

### ISSUE THREAD

**Issue by hymkor** [arxanas/scm-record#57]
### Description of the bug

- OS: Windows 11 , Terminal: both WindowsTerminal and Command Prompt
- The version of scm-record: the executable built with the latest commit ( 8df3f452eb826d52b14c40306e84e4bfb08ab3fc )
- **The colored line terminating with CRLF disappears when cursor moves there** (NG)

![scm-record-20240705](https://github.com/arxanas/scm-record/assets/3752189/d9bf859b-6df8-4f85-b5d6-709feb94e366)

[first.txt](https://github.com/user-attachments/files/16101204/first.txt)
[second.txt](https://github.com/user-attachments/files/16101205/second.txt)

### Expected behavior

Whether line terminates with LF or CRLF, the text where cursor exists does not disappear.

### Actual behavior

- **The colored line terminating with CRLF disappears when cursor moves there** (NG)
- When line terminates with only LF, the line does not disappear. (OK)

### Version of `rustc`

rustc 1.74.1 (a28077b28 2023-12-04)

**Comment by s4uliu5** [comment]
The same issue exists on linux too -- scm-diff-editor doest not work with CRLF files.

**Comment by arxanas** [comment]
I put up https://github.com/arxanas/scm-record/pull/61 for this. I'm not sure what the best way is to decide if a character is non-printing. I checked if the [Unicode width](https://github.com/unicode-rs/unicode-width) is zero.

**Comment by s4uliu5** [comment]
0d59b0fd23746f099ae10ee743bd4c6d3e6d4fea fixed the issue  for me :smile:

**Comment by hymkor** [comment]
I confirmed that it was fixed after `git pull && cargo build --release`.
And `jj split` by jj 0.19 with new scm-diff-editor.exe as a add-on also works as I expected.

@arxanas , @s4uliu5 , thank you !
