### ISSUE TITLE
cargo install --locked scm-diff-editor  failure

### ISSUE THREAD

**Issue by s4uliu5** [arxanas/scm-record#59]
### Description of the bug

Following `README.md` 

`cargo install --locked scm-diff-editor`

fails to install `scm-diff-editor`.

### Expected behavior

Successful installation.

### Actual behavior

```
$ cargo install --locked scm-diff-editor
    Updating crates.io index
error: could not find `scm-diff-editor` in registry `crates-io` with version `*`
```

### Version of `rustc`

rustc 1.74.1 (a28077b28 2023-12-04)

**Comment by arxanas** [comment]
Sorry for the confusion. That'll be the way to install it once it's released to crates.io. For now, you can install from source by adding `--git https://github.com/arxanas/scm-record` to your invocation.
