### ISSUE TITLE
Deleted files are not selected

### ISSUE THREAD

**Issue by FiloSottile** [arxanas/scm-record#82]
### Description of the bug

If I select a deleted file, both along with other changes, or alone, everything behaves as if I didn't.

<img width="681" alt="image" src="https://github.com/user-attachments/assets/7b2ede75-5359-4cf3-803b-099336f41cd6" />

```
$ jj squash -t vt -i
Error: No changes selected
```

**Comment by arxanas** [comment]
This one is specifically a jj integration bug, tracked here: https://github.com/jj-vcs/jj/issues/3702

**Comment by arxanas** [comment]
Thanks for posting, though. Since this is a common issue in jj, I've pinned this issue so that it can link to the authoritative jj issue, in case anyone else comes across this.

**Comment by jgilchrist** [comment]
@arxanas I think this can be closed now that https://github.com/jj-vcs/jj/issues/3702 is closed
